### ISSUE TITLE
Retrieving all of the messageId from the view

### ISSUE THREAD

**Issue by marconealberto** [hiroara/TiMessagesTableViewController#5]
Is there a way to retrieve the messageId for every sent message? right now I can get the messageId property only for the messages I send or the messages I click on.
I'm connecting this module to the Cloud.Chat and I need a way to associate the chatId from the Cloud to your messageId, and I would need something like this:

> var obj = view.sendMessage({text: 'Foo Foooo!!!', sender: 'hiro_ari'});
> console.log(obj.messageId);

so that if I want to remove a message from the server, I click on the balloon, I get your messageId and then I can ask the Cloud to remove the id corresponding to your messageId.

**Comment by hiroara** [comment]
Hi, I'm sorry for my late reply.
I have implemented this feature in #9 and already merged to master branch.
Please see if it is ok.
